// RootLayout.jsx
import React from 'react';
import PropTypes from 'prop-types';
import localFont from "next/font/local";
import "./globals.css";
import UserContextProvider from "@/context/UserContextProvider";
import Provider from "@/component/Provider";
import AppProviderBasic from "@/component/Navbar/SideBar";
import DashboardIcon from '@mui/icons-material/Dashboard';
import TimelineIcon from '@mui/icons-material/Timeline';

// Load custom fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const Navigation = [
  {
    kind: 'student',
    title: 'Student',
  },
  {
    segment: 'page',
    title: 'Page',
    icon: <DashboardIcon />,
  },
  {
    segment: 'page-2',
    title: 'Page 2',
    icon: <TimelineIcon />,
  },
  {
    segment: 'student1',
    title: 'Student',
    icon: <DashboardIcon />,
  },
];

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserContextProvider>
          <Provider>
            <AppProviderBasic navigation={Navigation}>
              {children}
            </AppProviderBasic>
          </Provider>
        </UserContextProvider>
      </body>
    </html>
  );
}

RootLayout.propTypes = {
  /**
   * Child components to be rendered inside the layout.
   */
  children: PropTypes.node.isRequired,
};
