// RootLayout.jsx
import React from "react";
import PropTypes from "prop-types";
import localFont from "next/font/local";
import "./globals.css";
import UserContextProvider from "@/context/UserContextProvider";
import Provider from "@/component/Provider";
import { ToastContainer } from "react-toastify";
import MiniDrawer from "@/component/Navbar/SideBar";

// Load custom fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.8/css/line.css"></link>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastContainer />
        <UserContextProvider>
          <Provider>
            <MiniDrawer>{children}</MiniDrawer>
          </Provider>
        </UserContextProvider>
      </body>
    </html>
  );
}

