export const routesUrl = {
  signIn: "/auth/signin",
  student: "/student",
  teacher: "/teacher",
  attendence: "/studentattendence",
  viewAttendence: "/viewattendence",
  home: "/",
  teacherleave: "/leaverequest",
  studentleave: "/studentleave",
  classroutine: "/classroutine",
  viewclassroutine:"/classroutine/checkclassroutine",
  exam:"/examination",
  examTable:"/examination/examschedule",
  library:"/library",
  bookissue:"/library/bookissue",
  record:"/bookissue",
};
